#!/bin/sh
TEMPFILE=$(mktemp)
DBFILE="$QSS_PATH"
function todelete()
{
	echo "DELETE FROM file WHERE path = '$1';" >> /"$TEMPFILE"
}

echo "BEGIN TRANSACTION;" >> /"$TEMPFILE"

sqlite3 "$DBFILE" "SELECT path FROM file;"| while read line ; do
[ -e "$line" ] || todelete "$line"
done

echo "COMMIT TRANSACTION;" >> /"$TEMPFILE"

sqlite3 "$DBFILE" < /"$TEMPFILE"




